import type { Content } from './types'

export const de: Content = {
  nav_btn_mac: 'Herunterladen',
  nav_btn_win: 'Herunterladen',

  hero_h1:  'Das digitale Museum\nIhrer Sammlung',
  hero_sub: 'Der elegante, einfache und flexible Weg,\nIhre Münzen und Banknoten zu ordnen, zu dokumentieren und zu genießen',
  hero_btn_mac: 'Herunterladen',
  hero_btn_win: 'Herunterladen',
  hero_mobile_notice: 'Legado ist eine Desktop-Anwendung.\nBesuchen Sie diese Seite von Ihrem Mac oder PC,\num sie herunterzuladen.',

  pasos_h2:  'Weil Ihre Sammlung\nmehr verdient\nals ein bloßes Inventar',
  pasos_sub: 'Legado ist der elegante, flexible und einfache Weg,\nIhre Stücke zu dokumentieren und zu zeigen',

  paso1_titulo: 'Von Numismatikern\nfür Numismatiker',
  paso1_body:   'Erfassen Sie jedes Exemplar einzeln oder importieren Sie die Daten Ihrer Sammlung mit einem Klick aus Excel oder einer CSV-Datei.',
  paso2_titulo: 'Mit einer Ästhetik auf der Höhe\nIhrer besten Stücke',
  paso2_body:   'Ordnen Sie jedem Exemplar automatisch Fotos zu und hängen Sie Videos, Dokumente, Links und Referenzen an. Alles jederzeit griffbereit.',
  paso3_titulo: 'Anpassbar an Ihre Art\nzu sammeln',
  paso3_body:   'Ordnen Sie Ihre Münzen und Banknoten, wie Sie möchten, und exportieren oder drucken Sie Ihre Daten, wann immer Sie sie brauchen.\nIhre Sammlung, Ihre Regeln.',
  paso4_titulo: 'Übersichtlich\nund einfach zu bedienen',
  paso4_body:   'Zeigen Sie Ihre Stücke auf Karten, vergleichen Sie Exemplare, halten Sie Notizen fest, planen Sie künftige Erwerbungen, erstellen Sie Etiketten und sehen Sie Ihre Kennzahlen.',

  sc_h2:  'Alles, was Sie brauchen,\nan einem Ort',
  sc_sub: 'Ein visuelles, praktisches und klares Erlebnis,\num Numismatik zu genießen',

  sc1_titulo: 'Ausführliche Datenblätter in Sekunden',
  sc1_desc:   'Übernehmen Sie Beschreibung und technische Angaben Ihrer Münzen und Banknoten aus Numista oder aus dem Katalog OCRE (römische Münzen) und ergänzen Sie den historischen Kontext mithilfe künstlicher Intelligenz.',
  sc2_titulo: 'Vergrößern\nund vergleichen',
  sc2_desc:   'Betrachten Sie zwei Exemplare nebeneinander und prüfen Sie mit der eingebauten Lupe Unterschiede, Varianten und Erhaltungsgrade.',
  sc3_titulo: 'Druckfertige Etiketten entwerfen',
  sc3_desc:   'Erzeugen Sie eigene Etiketten für Münztabletts und Vitrinen. Speichern Sie Vorlagen und behalten Sie in der ganzen Sammlung ein einheitliches Erscheinungsbild.',
  sc4_titulo: 'Ihre Sammlung auf die Karte bringen',
  sc4_desc:   'Zeigen Sie Ihre Stücke auf heutigen und historischen Karten, nach dem Ort der Münzstätte oder dem Ausgabeland.',
  sc_anota_titulo: 'Direkt auf die Bilder zeichnen',
  sc_anota_desc:   'Schreiben und zeichnen Sie auf den Fotos Ihrer Münzen, um Varianten zu kennzeichnen, Einzelheiten zu erklären oder Ihre Beobachtungen sichtbar festzuhalten.',
  sc_stats_titulo: 'Die eigenen Daten sichtbar machen',
  sc_stats_desc:   'Erzeugen Sie eigene Diagramme und Statistiken zu Emittenten, Münzstätten und weiteren Kriterien und sehen Sie die wichtigsten Kennzahlen Ihrer Sammlung.',
  sc5_titulo: 'Die nächsten Erwerbungen planen',
  sc5_desc:   'Halten Sie fest, welche Exemplare Sie suchen — mit Budget, gewünschter Erhaltung und allen weiteren Angaben. Richten Sie Erinnerungen ein, damit Sie keine Auktion und keine Messe verpassen.',

  feat_h2:  'Der Unterschied liegt\nim Detail',
  feat_sub: 'Alles, was Sie brauchen, um Ihre Münzen\nzu ordnen und zu genießen',

  f1_titulo: 'Jahre an Arbeit in Sekunden importieren',
  f1_desc:   'Importieren Sie Ihre Daten und Bilder automatisiert, bearbeiten Sie mehrere Exemplare zugleich und arbeiten Sie weiter, ohne von vorn zu beginnen. Ein Passwort schützt Ihre Privatsphäre zusätzlich.',
  f2_titulo: 'Eine Galerie, Ihrer Sammlung würdig',
  f2_desc:   'Durchstöbern Sie Ihre Münzen und Banknoten in sechs Ansichten. Suchen Sie nach Stichwörtern, setzen Sie eigene Filter und prüfen Sie jede Einzelheit mit der Lupe, während Sie das Datenblatt lesen.',
  f3_titulo: 'Jedes Exemplar in seinem Kontext',
  f3_desc:   'Legen Sie eigene Felder an und ordnen Sie sie nach Belieben. Bestimmen und dokumentieren Sie jedes Stück gründlich, mit Hilfe der Datenbanken von Numista und OCRE (römische Münzen) und künstlicher Intelligenz. Zeigen Sie Münzen und Banknoten gemeinsam oder getrennt.',
  f4_titulo: 'Einfälle, Erinnerungen und Anmerkungen',
  f4_desc:   'Halten Sie Beobachtungen und offene Aufgaben auf digitalen Haftnotizen fest. Schreiben Sie auf Fotos. Führen Sie eine genaue Liste der gesuchten Exemplare und lassen Sie sich an wichtige Termine erinnern.',
  f5_titulo: 'Ein anderer Blick auf Ihre Sammlung',
  f5_desc:   'Werten Sie Statistiken aus, erkennen Sie Entwicklungen und sehen Sie die Eckdaten Ihrer Sammlung: Anschaffungswert, geschätzter aktueller Wert und innerer Wert, mit tagesaktuellen Kursen für Gold und Silber.',
  f6_titulo: 'Ein Erlebnis nach Ihrem Maß',
  f6_desc:   'Bestimmen Sie selbst, wie Sie Ihre Sammlung ansehen und ordnen. Passen Sie Typographie, Farben, Etiketten, Datenblätter und Gestaltung an Ihre Art zu sammeln an.',

  faq_titulo: 'Fragen?',
  faq_sub:    'Hier die Antworten auf die häufigsten',
  faq1_q: 'Ist Legado nur für Münz- und Banknotensammler?',
  faq1_a: 'Nein. Die Anwendung ist zwar eigens für die Numismatik gemacht (Münzen, Banknoten, Jetons und Medaillen), doch ihr flexibles System lässt sich mühelos auch auf andere Sammelgebiete übertragen.',
  faq2_q: 'Kann ich Legado auf dem Smartphone oder Tablet nutzen?',
  faq2_a: 'Derzeit gibt es die Anwendung ausschließlich für den Schreibtisch, für macOS (Apple Silicon) und Windows (64 Bit). Sie ist für bequemes Arbeiten an einem großen Bildschirm gedacht: ausführliche Datenblätter, Vergleich von Exemplaren, Karten und Etiketten. Eine Version für Smartphone oder Tablet gibt es noch nicht.',
  faq3_q: 'Kann ich eine vorhandene Sammlung importieren?',
  faq3_a: 'Ja. Sie können Daten aus einer Tabellenkalkulation übernehmen. Legado lässt Sie wählen, welche Spalten importiert und welchen Feldern der Anwendung sie zugeordnet werden. Danach können Sie die Angaben einzeln oder gesammelt bearbeiten. Auch Bilder lassen sich importieren und über gemeinsame Codes automatisch ihren Exemplaren zuordnen.',
  faq4_q: 'Welche Angaben kann ich zu jedem Exemplar erfassen?',
  faq4_a: 'Sie können für jedes Stück eigene Felder festlegen, sie beliebig ordnen und Bilder, Videos, Dokumente sowie Links zu Webseiten oder zu anderen Dateien auf Ihrem Rechner anhängen. Alle Angaben lassen sich Ihren Bedürfnissen anpassen.',
  faq5_q: 'Brauche ich eine Internetverbindung, um Legado zu nutzen?',
  faq5_a: 'Für die Verwaltung und Abfrage der Daten arbeitet die Anwendung ohne Verbindung. Einige Funktionen benötigen Internet: die Karten, die Berechnung des inneren Werts, die Währungsumrechnung, der Zugriff auf die Datenbanken von Numista und OCRE sowie die Erzeugung von Inhalten mit künstlicher Intelligenz.',
  faq6_q: 'Ist der Download von Legado sicher? Wo werden meine Daten gespeichert?',
  faq6_a: 'Ja. Sie können Legado unbesorgt herunterladen. Das Programm wird ausschließlich über diese offizielle Website vertrieben und enthält weder Werbung noch zusätzliche Software. Die Daten liegen zudem lokal auf Ihrem Gerät oder in den externen Speicherdiensten, die Sie selbst einrichten. Legado speichert und verarbeitet diese Daten nicht auf eigenen Servern.',
  faq7_q: 'Muss ich ein laufendes Abonnement bezahlen?',
  faq7_a: 'Nein. Legado Basis ist kostenlos. Die Lizenz für Legado Pro wird einmalig bezahlt und ist an kein laufendes Abonnement gebunden.',
  faq8_q: 'Entstehen für Numista und die KI zusätzliche Kosten?',
  faq8_a: 'Der Zugriff auf die Datenbank von Numista erfordert einen kostenlosen API-Schlüssel, erhältlich auf Numista.com. Die Abfrage des OCRE-Katalogs ist kostenlos und braucht keinen Schlüssel. Legado steht weder mit Numista noch mit OCRE in Verbindung und ist für deren Bedingungen, Verfügbarkeit oder Preise nicht verantwortlich.\n\nFür die KI-Funktionen (Erzeugung des historischen Kontexts und Identifizierung von Exemplaren anhand von Fotos) enthält Legado Pro 500 Credits, die sich beide Funktionen teilen. Zusätzliche Pakete mit 200 Credits lassen sich in der Anwendung selbst erwerben. Jede Erzeugung eines historischen Kontexts kostet 1 Credit. Abfragen zur Identifizierung anhand von Bildern kosten je nach Verlässlichkeit des Ergebnisses 1 bis 5 Credits.',
  faq9_q: 'Auf wie vielen Rechnern kann ich Legado Pro nutzen?',
  faq9_a: 'Die Lizenz für Legado Pro erlaubt die Nutzung auf bis zu zwei Geräten gleichzeitig. Sie können die Lizenz außerdem in der Anwendung selbst auf einem Gerät deaktivieren, um sie freizugeben und auf einem anderen zu aktivieren — etwa beim Wechsel des Rechners.',
  faq10_q: 'Wie aktiviere ich mein Legado Pro?',
  faq10_a: 'Nach der Zahlung per Kreditkarte oder über PayPal erhalten Sie eine E-Mail mit einem Aktivierungscode. Geben Sie ihn im Bereich „Optionen“ der Anwendung ein.',

  comp_h2:  'Bringen Sie Ihre Sammlung\nauf die nächste Stufe',
  comp_sub: 'Beginnen Sie mit dem Wesentlichen\noder nutzen Sie das volle Erlebnis',
  cta_titulo: 'Machen Sie Ihre Sammlung\nzum Vermächtnis',
  cta_moneda_alt: 'Tetradrachme aus Athen mit der Eule der Athene',
  cta_lupa_hint: 'Fahren Sie mit dem Zeiger über die Münze',
  cta_puzzle_hint: 'Setzen Sie die Tetradrachme zusammen und erhalten Sie eine Überraschung',
  cta_puzzle_done: 'Und nun stellen Sie sich Ihre Sammlung genauso geordnet vor.',
  cta_discount_label: '5 % Rabatt auf Legado Pro mit dem Code',
  cta_code_copied: 'Code kopiert',
  dl_pro_label: 'Legado Pro',
  dl_pro_sub: 'Einmalige Zahlung · Volles Erlebnis',
  dl_basic_label: 'Legado Basis',
  dl_basic_sub: 'Kostenlos',

  footer_tagline: 'Das digitale Museum Ihrer Sammlung',
  footer_email:   'contacto@legadonumis.com',
  footer_copy:    '© 2026 Legado · legadonumis.com · Alle Rechte vorbehalten',
  legal_privacidad: 'Datenschutzerklärung',
  legal_terminos:   'Nutzungsbedingungen',
  legal_reembolso:  'Erstattungsrichtlinie',

  nav_link_exp:       'Funktionen',
  nav_link_ver:       'Preise',
  nav_link_faq:       'Fragen',
  nav_link_contact:   'Kontakt',
  nav_link_novedades: 'Neues',
  footer_col_product: 'Produkt',
  footer_col_support: 'Support',
  footer_col_legal:   'Rechtliches',

  url_download: '/de/download',
  url_privacy:  '/de/datenschutz',
  url_terms:    '/de/nutzungsbedingungen',
  url_refund:   '/de/erstattung',

  asset_hero:     '/assets/Hero.mp4',
  asset_sc1:      '/assets/FichaNumista.mp4',
  asset_sc2:      '/assets/FichaCompara.mp4',
  asset_sc3:      '/assets/FichaEtiqueta2.mp4',
  asset_sc4:      '/assets/FichaCecas.mp4',
  asset_sc_anota: '/assets/FichaAnota2.mp4',
  asset_sc_stats: '/assets/FichaStats.mp4',
  asset_sc5:      '/assets/FichaMetas.mp4',
  sc_consultas_titulo: 'Mit KI bestimmen\nund katalogisieren',
  sc_consultas_desc:   'Laden Sie das Foto einer Münze oder Banknote hoch, die Sie bestimmen möchten. Legado gleicht es mit Online-Katalogen ab und schlägt Ihnen mithilfe künstlicher Intelligenz die wahrscheinlichste Bestimmung vor.',
  asset_sc_consultas:  '/assets/FichaConsultas.mp4',
  sc_biblioteca_titulo: 'Sammlung und\nBibliothek verbinden',
  sc_biblioteca_desc:   'Ordnen Sie Bücher, Kataloge, Artikel und weitere Dokumente und verknüpfen Sie sie direkt mit Ihren Münzen und Banknoten, damit Sie sie immer zur Hand haben.',
  asset_sc_biblioteca:  '/assets/FichaBiblio.mp4',


  comp_groups: [
    {
      label: 'Ihre Sammlung',
      rows: [
        { feat: 'Erfasste Exemplare',              basico: 'Bis zu 50', pro: 'Unbegrenzt' },
        { feat: 'Import aus Excel und CSV',        basico: true,        pro: true },
        { feat: 'Automatisierter Fotoimport',      basico: true,        pro: true },
        { feat: 'Bilder, Videos und angehängte Dokumente', basico: true, pro: true },
      ],
    },
    {
      label: 'Dokumentation und Kataloge',
      rows: [
        { feat: 'Abfragen in Numista und im Online-Katalog römischer Münzen OCRE *', basico: true, pro: true },
        { feat: 'Erstellung von Informationen zum historischen Kontext der Exemplare mithilfe künstlicher Intelligenz', basico: false, pro: true },
        { feat: 'Identifizierung und Katalogisierung von Exemplaren mithilfe künstlicher Intelligenz', basico: false, pro: true },
        { feat: 'Anmerkungen auf Bildern', basico: false,      pro: true },
        { feat: 'Notizen (Post-its)',      basico: 'Bis zu 5', pro: 'Unbegrenzt' },
        { feat: 'Bibliothek bibliographischer Referenzen mit direkter Verknüpfung zu den Exemplaren', basico: false, pro: true },
      ],
    },
    {
      label: 'Anzeige',
      rows: [
        { feat: 'Bildergalerie (6 Modi)',           basico: true, pro: true },
        { feat: 'Vergleichsansicht für Exemplare',  basico: true, pro: true },
        { feat: 'Erkundung der Exemplare auf Karten', basico: true, pro: true },
        { feat: 'Heller Modus / Dunkler Modus',     basico: true, pro: true },
      ],
    },
    {
      label: 'Analyse und Planung',
      rows: [
        { feat: 'Statistiken',                     basico: false, pro: true },
        { feat: 'Anschaffungsplan und Erinnerungen', basico: 'Bis zu 5 Exemplare', pro: 'Unbegrenzt' },
      ],
    },
    {
      label: 'Export und Druck',
      rows: [
        { feat: 'Export nach Excel und CSV',        basico: 'Nur CSV', pro: true },
        { feat: 'Export von Datenblättern als PDF', basico: false,     pro: true },
        { feat: 'Etikettengenerator',               basico: false,     pro: true },
      ],
    },
    {
      label: 'Support und Aktualisierungen',
      rows: [
        { feat: 'Aktualisierungen',            basico: true,  pro: true },
        { feat: 'Zugriff auf neue Funktionen', basico: false, pro: true },
        { feat: 'Technischer Support',         basico: false, pro: true },
        { feat: 'Verfügbar auf Deutsch, Englisch, Französisch und Spanisch', basico: true, pro: true },
        { feat: 'macOS 11+ (Apple Silicon) · Windows 10+ (64 Bit)', basico: true, pro: true },
      ],
    },
  ],
  comp_plan_basic:         'Legado Basis',
  comp_plan_basic_sub:     'Der Anfang Ihres digitalen Museums',
  comp_plan_basic_price:   'Kostenlos',
  comp_plan_basic_cta_mac: 'Legado Basis\nherunterladen',
  comp_plan_basic_cta_win: 'Legado Basis\nherunterladen',
  comp_plan_pro:           'Legado Pro',
  comp_plan_pro_sub:       'Ihr digitales Museum ohne Grenzen',
  comp_price_launch:       'Einmalige Zahlung\nOhne Abonnement',
  comp_license_devices:    'Lizenz für zwei Geräte',
  comp_payment_note:       'Sichere Zahlung über LemonSqueezy',
  comp_plan_pro_cta:       'Legado Pro\nherunterladen',
  comp_plan_pro_cta_sub:   'und das Pro-Erlebnis freischalten',
  comp_footnote1:          '* Abfragen in Numista erfordern einen kostenlosen API-Schlüssel, erhältlich auf numista.com.',

  full_precio: '89',

  tm1_quote: 'Die Angaben zu meiner Sammlung lagen verstreut in verschiedenen Dateien und Notizen. In kurzer Zeit hatte ich alles nach Legado übertragen, und jetzt finde ich jede Angabe in Sekunden.',
  tm2_quote: 'Die Erinnerungen helfen mir, die Live-Auktionen nicht zu verpassen, die mich interessieren. Mit Legado plane ich besser und vermeide Spontankäufe.',
  tm3_quote: 'Ich habe andere Anwendungen ausprobiert, aber keine machte Lust, sie zu öffnen. Mit Legado ist meine Sammlung geordnet — und es macht mir obendrein Spaß.',
  tm4_quote: 'Wenn ich ein Stück untersuche, hebe ich meist Legenden, Zeichen oder kleine Details hervor. Diese Anmerkungen direkt auf dem Foto zu haben, hilft mir beim Auswerten und beim späteren Nachschlagen.',
  tm5_quote: 'Früher habe ich die Etiketten eines nach dem anderen vorbereitet. Jetzt erzeuge ich sie automatisch, ohne immer wieder dieselben Daten abzutippen, und stets im Design, das ich möchte.',
  tm6_quote: 'Jeder Sammler hat seine eigene Logik. Legado lässt mich meine Felder, meine Ordnung und mein Design festlegen. Endlich eine Anwendung, die sich mir anpasst und nicht umgekehrt.',
  tm7_quote: 'Jetzt kann ich meine gesamte Referenzliteratur mit jedem Stück verknüpfen und genau dann darauf zugreifen, wenn ich sie brauche.',
  tm8_quote: 'Das beste Vermächtnis ist nicht nur eine schöne Sammlung. Es sind auch die Schlüssel, um sie zu verstehen, zu bewahren und richtig zu betreuen.',
}
