import type { Content } from './types'

export const en: Content = {
  nav_btn_mac: 'Download',
  nav_btn_win: 'Download',

  hero_h1:  "Your collection's\ndigital home",
  hero_sub: 'An elegant, simple and flexible way to\norganize, document and enjoy your coins and banknotes',
  hero_btn_mac: 'Download',
  hero_btn_win: 'Download',
  hero_mobile_notice: 'Legado is a desktop app.\nVisit this page from your Mac or PC\nto download it.',

  pasos_h2:  'Because your collection\ndeserves more than\na simple inventory',
  pasos_sub: 'Legado is the elegant, flexible, and simple way\nto document and showcase your pieces',

  paso1_titulo: 'Built by and\nfor numismatists',
  paso1_body:   'Register every item individually or import your collection data from Excel or a CSV file with a single click.',
  paso2_titulo: 'An aesthetic worthy\nof your finest pieces',
  paso2_body:   'Automatically assign photos to each item and attach videos, documents, links, and references. Everything in one place, always accessible.',
  paso3_titulo: 'Adaptable to the way\nyou collect',
  paso3_body:   'Sort and filter your coins however you like, then export or print whenever you need.\nYour collection, your rules.',
  paso4_titulo: 'Intuitive\nand easy to use',
  paso4_body:   'View your items on maps, compare examples, keep notes, plan future acquisitions, create labels, and explore metrics.',

  sc_h2:  'Everything you need,\nin one place',
  sc_sub: 'A visual, practical, and intuitive experience\nfor enjoying numismatics',

  sc1_titulo: 'Create detailed records in seconds',
  sc1_desc:   'Import descriptions and technical data for your coins and banknotes from Numista or from the OCRE catalog (Roman coinage), and add historical context with the help of artificial intelligence.',
  sc2_titulo: 'Zoom in and\ncompare',
  sc2_desc:   'View two pieces side by side and use the built-in magnifier to examine differences, varieties, and grades.',
  sc3_titulo: 'Design labels ready to print',
  sc3_desc:   'Generate custom labels to place next to each coin in trays or display cases. Save templates and keep a consistent look across your entire collection.',
  sc4_titulo: 'Put your collection on the map',
  sc4_desc:   'View your pieces on modern and ancient Roman Empire maps, in a visual and intuitive experience.',
  sc_anota_titulo: 'Annotate directly on images',
  sc_anota_desc:   'Write and draw on your coin images to identify varieties, highlight relevant elements, or document your observations in a visual way.',
  sc_stats_titulo: 'Visualize your data',
  sc_stats_desc:   'Generate custom charts and statistics by issuer, mint, and other criteria, and explore the key indicators of your collection.',
  sc5_titulo: 'Plan your next acquisitions',
  sc5_desc:   "Keep track of the pieces you want to acquire — with your budget, desired grades, and any other relevant details. Set reminders so you never miss an auction, fair, or convention.",

  feat_h2:  'The difference is\nin the details',
  feat_sub: 'Everything you need to organize\nand appreciate your coins',

  f1_titulo: 'Import years of work in seconds',
  f1_desc:   'Import your data and images automatically, edit multiple pieces at once, and pick up right where you left off. Add a password for extra privacy.',
  f2_titulo: 'A gallery worthy of your collection',
  f2_desc:   'Browse your coins and banknotes in six different view modes. Search by keyword, apply custom filters, and zoom in on any detail with the built-in magnifier while reading the full record.',
  f3_titulo: 'Every piece, in context',
  f3_desc:   'Add fields, arrange them as you like, and document each piece in depth, with help from the Numista and OCRE (Roman coinage) databases and AI. View your coins and banknotes together or separately.',
  f4_titulo: 'Ideas, reminders, and notes',
  f4_desc:   "Use digital sticky notes to track observations and to-dos. Annotate photos. Keep a detailed list of the pieces you're looking for and get reminders for important dates.",
  f5_titulo: 'A fresh perspective on your collection',
  f5_desc:   'Analyze stats, identify trends, and view key data about your collection — including acquisition value, estimated current value, and intrinsic value, with live gold and silver prices.',
  f6_titulo: 'An experience built around you',
  f6_desc:   'Customize how you view and organize your collection. Adjust fonts, colors, labels, record layouts, and visual elements to make Legado feel like yours.',

  faq_titulo: 'Questions?',
  faq_sub:    "We've got answers",
  faq1_q: 'Is Legado only for coin and banknote collectors?',
  faq1_a: "No. While it's designed specifically for numismatics (coins, banknotes, tokens, and medals), its flexible system makes it easy to adapt to other types of collections.",
  faq2_q: 'Can I use Legado on my phone or tablet?',
  faq2_a: 'For now, the app is desktop-only, available for macOS (Apple Silicon) and Windows (64-bit). It is designed for comfortable work on a large screen — detailed records, side-by-side comparison, maps, and labels. There is no mobile or tablet version yet.',
  faq3_q: 'Can I import an existing collection?',
  faq3_a: 'Yes. You can pull data from a spreadsheet. Legado lets you choose which columns to import and how to map them to the app\'s fields. You can then edit records individually or in bulk. You can also import images and have them assigned automatically to their corresponding pieces using shared codes.',
  faq4_q: 'What information can I add to each piece?',
  faq4_a: 'You can define custom fields for each piece, arrange them however you like, and attach images, videos, documents, and links to web resources or other files on your computer. Everything can be tailored to your needs.',
  faq5_q: 'Do I need an internet connection to use Legado?',
  faq5_a: 'The app works offline for managing and browsing your data. Some features — the map, live bullion prices, currency conversion, Numista and OCRE integration, and AI content generation — require an internet connection.',
  faq6_q: 'Is Legado safe to download? Where is my data stored?',
  faq6_a: 'Yes. You can download Legado with confidence. The app is distributed exclusively through this official website and includes no ads or bundled software. Your data is stored locally on your device, or in an external storage service you configure yourself. Legado does not store or process your data on its own servers.',
  faq7_q: 'Is there a recurring subscription?',
  faq7_a: 'No. Legado Basic is free. The Legado Pro license is a one-time purchase with no subscription.',
  faq8_q: 'Is there an extra cost for Numista and AI?',
  faq8_a: 'Numista access requires a free API key from Numista.com. Note that Legado is not affiliated with Numista and is not responsible for their terms, availability, or pricing. The OCRE catalog is free to query and requires no key. In addition, Legado Pro includes 500 credits for generating historical context about coins and banknotes. Additional credit packs can be purchased.',
  faq9_q: 'On how many computers can I use Legado Pro?',
  faq9_a: 'A Legado Pro license lets you use the app on up to two devices at the same time. You can also deactivate the license on one computer from within the app to free it up and activate it on another — for example, when switching machines.',
  faq10_q: 'How do I activate my Legado Pro?',
  faq10_a: "After completing your payment by credit card or PayPal, you'll receive an email with an activation code. Enter it in the Settings section of the app.",

  comp_h2:  'Take your collection\nto the next level',
  comp_sub: 'Start with the essentials or\nunlock the full experience',
  cta_titulo: 'Turn your collection\ninto a legacy',
  cta_moneda_alt: 'Athenian tetradrachm with the owl of Athena',
  cta_lupa_hint: 'Hover over the coin',
  cta_puzzle_hint: 'Rebuild the tetradrachm and unlock a surprise',
  cta_puzzle_done: 'Now picture your collection, this organized.',
  cta_discount_label: '10% off Legado Pro with code',
  cta_code_copied: 'Code copied',
  dl_pro_label: 'Legado Pro',
  dl_pro_sub: 'One-time payment · Full experience',
  dl_basic_label: 'Legado Basic',
  dl_basic_sub: 'Free',

  footer_tagline: "Your collection's digital home",
  footer_email:   'contacto@legadonumis.com',
  footer_copy:    '© 2026 Legado · legadonumis.com · All rights reserved',
  legal_privacidad: 'Privacy Policy',
  legal_terminos:   'Terms of Use',
  legal_reembolso:  'Refund Policy',

  nav_link_exp:       'Features',
  nav_link_ver:       'Pricing',
  nav_link_faq:       'FAQ',
  nav_link_contact:   'Contact',
  nav_link_novedades: 'Updates',
  footer_col_product: 'Product',
  footer_col_support: 'Support',
  footer_col_legal:   'Legal',

  url_download: 'download.html',
  url_privacy:  'privacy.html',
  url_terms:    'terms.html',
  url_refund:   'refund-policy.html',

  asset_hero:     '/assets/Hero.mp4',
  asset_sc1:      '/assets/FichaNumista.mp4',
  asset_sc2:      '/assets/FichaCompara.mp4',
  asset_sc3:      '/assets/FichaEtiqueta2.mp4',
  asset_sc4:      '/assets/FichaCecas.mp4',
  asset_sc_anota: '/assets/FichaAnota2.mp4',
  asset_sc_stats: '/assets/FichaStats.mp4',
  asset_sc5:      '/assets/FichaMetas.mp4',

  comp_groups: [
    {
      label: 'Your collection',
      rows: [
        { feat: 'Registered pieces',            basico: 'Up to 50', pro: 'Unlimited' },
        { feat: 'Import from Excel & CSV',      basico: true,       pro: true },
        { feat: 'Automated photo import',       basico: true,       pro: true },
        { feat: 'Photos, videos & documents',   basico: true,       pro: true },
      ],
    },
    {
      label: 'Documentation & catalogs',
      rows: [
        { feat: 'Numista & OCRE Roman coinage catalog lookups *', basico: true, pro: true },
        // TODO: restaurar cta { label: 'Need more?', url: <landing de packs en LemonSqueezy> } cuando exista la landing
        { feat: 'AI-generated historical context information', basico: false, pro: '500 queries included\n(buy more from the app)' },
        { feat: 'Photo annotations', basico: false,     pro: true },
        { feat: 'Sticky notes',      basico: 'Up to 5', pro: 'Unlimited' },
      ],
    },
    {
      label: 'Views',
      rows: [
        { feat: 'Image gallery (6 modes)',   basico: true, pro: true },
        { feat: 'Side-by-side comparison',   basico: true, pro: true },
        { feat: 'Explore pieces on maps',    basico: true, pro: true },
        { feat: 'Light mode / Dark mode',    basico: true, pro: true },
      ],
    },
    {
      label: 'Analysis & planning',
      rows: [
        { feat: 'Statistics',                   basico: false, pro: true },
        { feat: 'Acquisition plan & reminders', basico: 'Up to 5 pieces', pro: 'Unlimited' },
      ],
    },
    {
      label: 'Export & printing',
      rows: [
        { feat: 'Export to Excel & CSV',       basico: 'CSV only', pro: true },
        { feat: 'Export coin records to PDF',  basico: false,      pro: true },
        { feat: 'Label designer',              basico: false,      pro: true },
      ],
    },
    {
      label: 'Support & updates',
      rows: [
        { feat: 'Updates',                          basico: true,  pro: true },
        { feat: 'Access to new features',           basico: false, pro: true },
        { feat: 'Technical support',                basico: false, pro: true },
        { feat: 'Available in Spanish and English', basico: true,  pro: true },
        { feat: 'macOS 11+ (Apple Silicon) · Windows 10+ (64-bit)', basico: true, pro: true },
      ],
    },
  ],
  comp_plan_basic:         'Legado Basic',
  comp_plan_basic_sub:     'Your digital museum, for free',
  comp_plan_basic_price:   'Free',
  comp_plan_basic_cta_mac: 'Download\nLegado Basic',
  comp_plan_basic_cta_win: 'Download\nLegado Basic',
  comp_plan_pro:           'Legado Pro',
  comp_plan_pro_sub:       'Your digital museum, unlimited',
  comp_price_launch:       'One-time payment\nNo subscriptions',
  comp_license_devices:    'License for two devices',
  comp_payment_note:       'Secure payment via LemonSqueezy',
  comp_plan_pro_cta:       'Download\nLegado Pro',
  comp_plan_pro_cta_sub:   'and Activate the Pro Experience',
  comp_footnote1:          '* Numista lookups require a free API key available at numista.com.',

  trial_badge:  'Basic',
  trial_precio: 'Free',
  trial_nota:   'No time limit',
  trial_items: [
    'Up to 50 cataloged pieces',
    '5 AI assistant uses',
    'Full photo gallery',
    'Interactive mint map',
    'No time limit',
  ],
  trial_cta: 'Download free',
  full_tag:    'Pro',
  full_badge:  'Most popular',
  full_precio: '89',
  full_divisa: '€',
  full_nota:   'One-time payment · no subscription',
  full_btn:    'Get Legado Pro',
  full_items: [
    'Unlimited pieces',
    'Unlimited AI assistant',
    'Export to Excel, CSV & PDF',
    'Tray label designer',
    'Two years of updates',
    'Email support',
  ],

  tm1_quote: 'My collection data was scattered across different files and notes. In no time I moved everything to Legado, and now I can find any detail in seconds.',
  tm2_quote: 'The reminders help me keep track of live auctions that interest me. With Legado I can plan better and avoid impulse purchases.',
  tm3_quote: "I've tried other apps, but none of them made me want to open them. With Legado my collection is organised and, on top of that, I'm actually having fun.",
  tm4_quote: 'When I study a piece, I like to highlight legends, marks or small details. Having those notes directly on the photograph helps me analyse and refer back to them later.',
  tm5_quote: 'I used to prepare labels one by one. Now I generate them automatically without copying data over and over, and always with the layout I want.',
  tm6_quote: "Every collector has their own logic. Legado lets me define my own fields, my own order, and my own design. Finally an app that adapts to me — not the other way round.",
}
