import type { Content } from './types'

export const es: Content = {
  nav_btn_mac: 'Descargar',
  nav_btn_win: 'Descargar',

  hero_h1:  'El museo digital\nde tu colección',
  hero_sub: 'Una manera elegante, sencilla y flexible de\norganizar, documentar y disfrutar tus monedas y billetes',
  hero_btn_mac: 'Descargar',
  hero_btn_win: 'Descargar',
  hero_mobile_notice: 'Legado es una aplicación de escritorio.\nVisita esta web desde tu Mac o PC\npara descargarla.',

  pasos_h2:  'Porque tu colección\nmerece más que\nun simple inventario',
  pasos_sub: 'Legado es la forma elegante, flexible y sencilla\nde documentar y visualizar tus piezas',

  paso1_titulo: 'Diseñado por y\npara numismáticos',
  paso1_body:   'Registra cada ejemplar individualmente o importa los datos de tu colección desde Excel o un archivo CSV con un solo clic.',
  paso2_titulo: 'Con una estética a la altura\nde tus mejores piezas',
  paso2_body:   'Asigna automáticamente fotos a cada ejemplar y adjunta vídeos, documentos, enlaces y referencias. Todo siempre accesible.',
  paso3_titulo: 'Adaptable a tu forma\nde coleccionar',
  paso3_body:   'Ordena tus monedas y billetes como prefieras, y exporta o imprime tus datos cuando lo necesites.\nTu colección, tus reglas.',
  paso4_titulo: 'Intuitivo\ny fácil de usar',
  paso4_body:   'Visualiza tus piezas sobre mapas, compara ejemplares, guarda notas, planifica futuras adquisiciones, crea etiquetas y consulta métricas.',

  sc_h2:  'Todo lo que necesitas,\nen un solo lugar',
  sc_sub: 'Una experiencia visual, práctica e intuitiva\npara disfrutar la numismática',

  sc1_titulo: 'Crea fichas detalladas en segundos',
  sc1_desc:   'Importa la descripción y la información técnica de tus monedas y billetes desde Numista o desde el catálogo OCRE (moneda romana), y añade información de su contexto histórico con ayuda de inteligencia artificial.',
  sc2_titulo: 'Amplía y\ncompara',
  sc2_desc:   'Visualiza dos ejemplares simultáneamente y utiliza una lupa integrada para examinar diferencias, variantes y estados de conservación.',
  sc3_titulo: 'Diseña etiquetas listas para imprimir',
  sc3_desc:   'Genera etiquetas personalizadas para colocar junto a cada moneda en bandejas o expositores. Guarda plantillas y mantén una presentación uniforme en toda tu colección.',
  sc4_titulo: 'Pon tu colección en el mapa',
  sc4_desc:   'Visualiza tus piezas sobre mapas actuales y del Imperio romano en una experiencia visual e intuitiva.',
  sc_anota_titulo: 'Anota directamente sobre imágenes',
  sc_anota_desc:   'Escribe y dibuja sobre las imágenes de tus monedas para identificar variantes, explicar elementos relevantes o documentar tus observaciones de forma visual.',
  sc5_titulo: 'Planifica tus próximas adquisiciones',
  sc5_desc:   'Registra los ejemplares que quieres conseguir, con tu presupuesto, conservación deseada y cualquier otro detalle relevante. Activa recordatorios para no olvidar fechas de subastas, convenciones, etc.',

  feat_h2:  'La diferencia está\nen los detalles',
  feat_sub: 'Todo lo que necesitas para organizar\ny apreciar tus monedas',

  f1_titulo: 'Importa años de trabajo en segundos',
  f1_desc:   'Importa tus datos e imágenes de forma automatizada, edita múltiples ejemplares a la vez y continúa trabajando sin empezar desde cero. Añade una contraseña para mayor privacidad.',
  f2_titulo: 'Una galería digna de tu colección',
  f2_desc:   'Explora tus monedas y billetes en seis modos de visualización distintos. Busca por palabras clave, aplica filtros personalizados y examina cada detalle con lupa mientras consultas su ficha técnica.',
  f3_titulo: 'Cada ejemplar, en su contexto',
  f3_desc:   'Añade campos, ordénalos a tu gusto y documenta cada pieza en profundidad, con ayuda de las bases de datos de Numista y OCRE (moneda romana) y de la inteligencia artificial. Visualiza tus monedas y billetes, juntos o por separado.',
  f4_titulo: 'Ideas, recordatorios y anotaciones',
  f4_desc:   'Utiliza post-its digitales para guardar observaciones y tareas pendientes. Realiza anotaciones sobre fotos. Mantén una lista detallada de los ejemplares que buscas y recibe recordatorios de fechas importantes.',
  f5_titulo: 'Una perspectiva diferente de tu colección',
  f5_desc:   'Analiza estadísticas, identifica tendencias, y consulta datos clave sobre tu colección, incluyendo su valor de adquisición, valor actual estimado y valor intrínseco, con precios actualizados del oro y la plata.',
  f6_titulo: 'Una experiencia hecha a tu medida',
  f6_desc:   'Personaliza la forma en que visualizas y organizas tu colección. Ajusta tipografías, colores, etiquetas, fichas y elementos visuales para adaptar Legado a tu manera de coleccionar.',

  faq_titulo: '¿Preguntas?',
  faq_sub:    'Te respondemos las dudas más habituales',
  faq1_q: '¿Es Legado solo para coleccionistas de monedas y billetes?',
  faq1_a: 'No. Aunque está diseñado específicamente para numismática (monedas, billetes, fichas y medallas), su sistema flexible permite adaptarse fácilmente a otros tipos de colecciones.',
  faq2_q: '¿Puedo usar Legado en el móvil o la tablet?',
  faq2_a: 'Por el momento, la aplicación es exclusivamente de escritorio, disponible para macOS (Apple Silicon) y Windows (64 bits). Está diseñada para trabajar con comodidad frente a una pantalla grande: fichas detalladas, comparación de ejemplares, mapas y etiquetas. Todavía no existe versión para móvil ni tablet.',
  faq3_q: '¿Puedo importar una colección existente?',
  faq3_a: 'Sí. Puedes extraer datos desde una hoja de cálculo. Legado te permite seleccionar qué columnas importar y cómo asignarlas a los campos de la aplicación. Después puedes editar la información de forma individual o en bloque. También puedes importar imágenes y asignarlas automáticamente a sus ejemplares, utilizando códigos compartidos.',
  faq4_q: '¿Qué tipo de información puedo añadir a cada ejemplar?',
  faq4_a: 'Puedes definir campos personalizados para cada pieza, organizarlos como quieras, y adjuntar imágenes, vídeos, documentos y enlaces a recursos web u otros archivos en tu ordenador. Toda la información puede ajustarse según tus necesidades.',
  faq5_q: '¿Necesito conexión a Internet para usar Legado?',
  faq5_a: 'La aplicación funciona offline para la gestión y consulta de datos. Algunas funciones como el mapa, el cálculo del valor intrínseco, la conversión entre divisas, el acceso a las bases de datos de Numista y OCRE y la generación de contenido mediante inteligencia artificial requieren conexión a Internet.',
  faq6_q: '¿Es seguro descargar Legado? ¿Dónde se guardan mis datos?',
  faq6_a: 'Sí. Puedes descargar Legado con tranquilidad. El programa se distribuye únicamente desde esta web oficial y no incluye publicidad ni software adicional. Además, los datos se almacenan localmente en tu dispositivo o en servicios externos de almacenamiento que tú configures. Legado no almacena ni procesa esos datos en sus propios servidores.',
  faq7_q: '¿Tengo que pagar alguna suscripción periódica?',
  faq7_a: 'No. Legado Básico es gratuito. La licencia de Legado Pro implica un pago único y no está sujeta a una suscripción periódica.',
  faq8_q: '¿El uso de Numista y la IA tiene algún coste adicional?',
  faq8_a: 'El acceso a la base de datos de Numista requiere una clave API gratuita disponible en Numista.com. Cabe mencionar que Legado no está vinculado a Numista ni es responsable de sus condiciones, disponibilidad o precios. La consulta del catálogo OCRE es gratuita y no requiere clave. Además, Legado Pro incluye en su precio 500 créditos para generar información contextual histórica de monedas y billetes. Es posible adquirir paquetes de créditos adicionales.',
  faq9_q: '¿En cuántos ordenadores puedo usar Legado Pro?',
  faq9_a: 'La licencia de Legado Pro permite usar la aplicación en hasta dos dispositivos simultáneamente. Además, puedes desactivar la licencia en un equipo desde la propia aplicación para liberarla y activarla en otro, por ejemplo al cambiar de ordenador.',
  faq10_q: '¿Cómo activo mi Legado Pro?',
  faq10_a: 'Tras realizar el pago con tarjeta de crédito o a través de PayPal, recibirás un correo electrónico con un código de activación. Introdúcelo en la sección "Ajustes" de la aplicación.',

  comp_h2:  'Lleva tu colección\nal siguiente nivel',
  comp_sub: 'Comienza con lo esencial o\naccede a la experiencia completa',
  cta_titulo: 'Convierte tu colección\nen un legado',
  cta_moneda_alt: 'Tetradracma de Atenas con la lechuza de Atenea',
  cta_lupa_hint: 'Pasa el cursor sobre la moneda',
  cta_puzzle_hint: 'Reconstruye el tetradracma y desbloquea una sorpresa',
  cta_puzzle_done: 'Ahora imagina tu colección así de organizada.',
  cta_discount_label: '10% de descuento en Legado Pro con el código',
  cta_code_copied: 'Código copiado',
  dl_pro_label: 'Legado Pro',
  dl_pro_sub: 'Pago único · Experiencia completa',
  dl_basic_label: 'Legado Básico',
  dl_basic_sub: 'Gratis',

  footer_tagline: 'El museo digital de tu colección',
  footer_email:   'contacto@legadonumis.com',
  footer_copy:    '© 2026 Legado · legadonumis.com · Todos los derechos reservados',
  legal_privacidad: 'Política de privacidad',
  legal_terminos:   'Términos de uso',
  legal_reembolso:  'Política de reembolso',

  nav_link_exp:       'Características',
  nav_link_ver:       'Precios',
  nav_link_faq:       'Preguntas',
  nav_link_contact:   'Contacto',
  nav_link_novedades: 'Novedades',
  footer_col_product: 'Producto',
  footer_col_support: 'Soporte',
  footer_col_legal:   'Legal',

  url_download: '/descarga',
  url_privacy:  '/privacidad',
  url_terms:    '/terminos',
  url_refund:   '/reembolso',

  asset_hero:     '/assets/Hero.mp4',
  asset_sc1:      '/assets/FichaNumista.mp4',
  asset_sc2:      '/assets/FichaCompara.mp4',
  asset_sc3:      '/assets/FichaEtiqueta2.mp4',
  asset_sc4:      '/assets/FichaCecas.mp4',
  asset_sc_anota: '/assets/FichaAnota2.mp4',
  asset_sc5:      '/assets/FichaMetas.mp4',

  comp_groups: [
    {
      label: 'Tu colección',
      rows: [
        { feat: 'Ejemplares registrados',                  basico: 'Hasta 50', pro: 'Ilimitados' },
        { feat: 'Importación desde Excel y CSV',           basico: true,       pro: true },
        { feat: 'Importación automatizada de fotografías', basico: true,       pro: true },
        { feat: 'Imágenes, vídeos y documentos adjuntos',  basico: true,       pro: true },
      ],
    },
    {
      label: 'Documentación y catálogos',
      rows: [
        { feat: 'Consultas a Numista y al catálogo online de monedas romanas OCRE *', basico: true, pro: true },
        // TODO: restaurar cta { label: '¿Necesitas más?', url: <landing de packs en LemonSqueezy> } cuando exista la landing
        { feat: 'Generación de información sobre contexto histórico con ayuda de inteligencia artificial', basico: false, pro: '500 consultas incluidas' },
        { feat: 'Anotaciones sobre imágenes', basico: false,     pro: true },
        { feat: 'Post-Its',                   basico: 'Hasta 5', pro: 'Ilimitados' },
      ],
    },
    {
      label: 'Visualización',
      rows: [
        { feat: 'Galería de imágenes (6 modos)',         basico: true, pro: true },
        { feat: 'Visor comparativo de ejemplares',       basico: true, pro: true },
        { feat: 'Exploración de ejemplares sobre mapas', basico: true, pro: true },
      ],
    },
    {
      label: 'Análisis y planificación',
      rows: [
        { feat: 'Estadísticas',                          basico: false, pro: true },
        { feat: 'Plan de adquisiciones y recordatorios', basico: 'Hasta 5 ejemplares', pro: 'Ilimitados' },
      ],
    },
    {
      label: 'Exportación e impresión',
      rows: [
        { feat: 'Exportación a Excel y CSV',    basico: 'Solo CSV', pro: true },
        { feat: 'Exportación de fichas en PDF', basico: false,      pro: true },
        { feat: 'Diseñador de etiquetas',       basico: false,      pro: true },
      ],
    },
    {
      label: 'Soporte y actualizaciones',
      rows: [
        { feat: 'Acceso a nuevas funciones',     basico: false, pro: true },
        { feat: 'Soporte técnico',               basico: false, pro: true },
        { feat: 'Versiones en español e inglés', basico: true,  pro: true },
        { feat: 'macOS 11+ (Apple Silicon) · Windows 10+ (64 bits)', basico: true, pro: true },
      ],
    },
  ],
  comp_plan_basic:         'Legado Básico',
  comp_plan_basic_sub:     'El inicio de tu museo digital',
  comp_plan_basic_price:   'Gratis',
  comp_plan_basic_cta_mac: 'Descargar\nLegado Básico',
  comp_plan_basic_cta_win: 'Descargar\nLegado Básico',
  comp_plan_pro:           'Legado Pro',
  comp_plan_pro_sub:       'Tu museo digital sin límites',
  comp_price_launch:       'Pago único · Sin suscripciones',
  comp_license_devices:    'Licencia para dos dispositivos',
  comp_payment_note:       'Pago seguro vía LemonSqueezy',
  comp_plan_pro_cta:       'Descargar\nLegado Pro',
  comp_plan_pro_cta_sub:   'y Activa Experiencia Pro',
  comp_footnote1:          '* Las consultas a Numista requieren una clave API gratuita disponible en numista.com.',

  trial_badge:  'Básico',
  trial_precio: 'Gratis',
  trial_nota:   'Sin límite de tiempo',
  trial_items: [
    'Hasta 50 ejemplares catalogados',
    '5 usos del asistente IA',
    'Galería fotográfica completa',
    'Mapa de cecas interactivo',
    'Sin límite de tiempo',
  ],
  trial_cta: 'Descargar gratis',
  full_tag:    'Pro',
  full_badge:  'Más popular',
  full_precio: '89',
  full_divisa: '€',
  full_nota:   'Pago único · sin suscripción',
  full_btn:    'Obtener Legado Pro',
  full_items: [
    'Ejemplares ilimitados',
    'Asistente IA ilimitado',
    'Exportar a Excel, CSV y PDF',
    'Etiquetador de bandejas',
    'Actualizaciones durante dos años',
    'Soporte técnico por correo',
  ],

  tm1_quote: 'Tenía la información de mi colección repartida entre distintos archivos y notas. En muy poco tiempo conseguí trasladarlo todo a Legado y ahora encuentro cualquier dato en cuestión de segundos.',
  tm2_quote: 'Los recordatorios me ayudan a no perderme las subastas en vivo que me interesan. Con Legado puedo planificar mejor y evitar compras impulsivas.',
  tm3_quote: 'He probado otras aplicaciones, pero ninguna me daba ganas de abrirla. Con Legado tengo la colección organizada y, además, me divierto.',
  tm4_quote: 'Cuando estudio una pieza, suelo destacar leyendas, marcas o pequeños detalles. Tener esas anotaciones directamente sobre la fotografía me ayuda a analizarlas y consultarlas más adelante.',
  tm5_quote: 'Antes preparaba las etiquetas una por una. Ahora las genero automáticamente sin tener que copiar datos una y otra vez, y siempre con el diseño que quiero.',
  tm6_quote: 'Cada coleccionista tiene su propia lógica. Legado me deja definir mis propios campos, mi propio orden y mi propio diseño. Por fin una app que se adapta a mí y no al revés.',
}
