import type { Content } from './types'

export const fr: Content = {
  nav_btn_mac: 'Télécharger',
  nav_btn_win: 'Télécharger',

  hero_h1:  'Le musée numérique\nde votre collection',
  hero_sub: 'La manière élégante, simple et souple\nd’organiser, documenter et savourer vos monnaies et billets',
  hero_btn_mac: 'Télécharger',
  hero_btn_win: 'Télécharger',
  hero_mobile_notice: 'Legado est une application de bureau.\nVisitez ce site depuis votre Mac ou votre PC\npour la télécharger.',

  pasos_h2:  'Parce que votre collection\nmérite mieux\nqu’un simple inventaire',
  pasos_sub: 'Legado est la façon élégante, souple et simple\nde documenter et de mettre en valeur vos pièces',

  paso1_titulo: 'Conçu par des numismates\npour des numismates',
  paso1_body:   'Enregistrez chaque pièce une à une ou importez les données de votre collection depuis Excel ou un fichier CSV, d’un seul clic.',
  paso2_titulo: 'Avec une esthétique à la hauteur\nde vos plus belles pièces',
  paso2_body:   'Attribuez automatiquement les photos à chaque pièce et joignez vidéos, documents, liens et références. Tout reste accessible, toujours.',
  paso3_titulo: 'Adaptable à votre façon\nde collectionner',
  paso3_body:   'Classez vos monnaies et billets comme vous l’entendez, et exportez ou imprimez vos données quand vous en avez besoin.\nVotre collection, vos règles.',
  paso4_titulo: 'Intuitif\net facile à utiliser',
  paso4_body:   'Visualisez vos pièces sur des cartes, comparez-les, gardez vos notes, planifiez vos futures acquisitions, créez des étiquettes et consultez vos statistiques.',

  sc_h2:  'Tout ce dont vous avez besoin,\nau même endroit',
  sc_sub: 'Une expérience visuelle, pratique et intuitive\npour savourer la numismatique',

  sc1_titulo: 'Créez des fiches détaillées en quelques secondes',
  sc1_desc:   'Importez la description et les données techniques de vos monnaies et billets depuis Numista ou depuis le catalogue OCRE (monnaie romaine), et ajoutez leur contexte historique avec l’aide de l’intelligence artificielle.',
  sc2_titulo: 'Agrandissez\net comparez',
  sc2_desc:   'Affichez deux pièces côte à côte et servez-vous de la loupe intégrée pour examiner différences, variantes et états de conservation.',
  sc3_titulo: 'Composez des étiquettes prêtes à imprimer',
  sc3_desc:   'Générez des étiquettes personnalisées à placer auprès de chaque monnaie, dans un plateau ou une vitrine. Enregistrez vos modèles et gardez une présentation uniforme dans toute la collection.',
  sc4_titulo: 'Mettez votre collection sur la carte',
  sc4_desc:   'Visualisez vos pièces sur des cartes actuelles et historiques, selon le lieu de l’atelier monétaire ou le pays d’émission.',
  sc_anota_titulo: 'Annotez directement sur les images',
  sc_anota_desc:   'Écrivez et dessinez sur les photographies de vos monnaies pour repérer des variantes, expliquer un élément ou consigner vos observations de façon visuelle.',
  sc_stats_titulo: 'Visualisez vos données',
  sc_stats_desc:   'Générez des graphiques et des statistiques sur mesure — par émetteur, par atelier monétaire ou selon d’autres critères — et consultez les indicateurs clés de votre collection.',
  sc5_titulo: 'Planifiez vos prochaines acquisitions',
  sc5_desc:   'Notez les pièces que vous cherchez, avec votre budget, l’état de conservation souhaité et tout autre détail utile. Activez des rappels pour ne manquer ni une vente aux enchères ni un salon.',

  feat_h2:  'La différence tient\naux détails',
  feat_sub: 'Tout ce qu’il faut pour organiser\net apprécier vos monnaies',

  f1_titulo: 'Importez des années de travail en quelques secondes',
  f1_desc:   'Importez vos données et vos images automatiquement, modifiez plusieurs pièces à la fois et reprenez votre travail là où vous l’aviez laissé. Ajoutez un mot de passe pour plus de confidentialité.',
  f2_titulo: 'Une galerie digne de votre collection',
  f2_desc:   'Parcourez vos monnaies et billets dans six modes d’affichage. Cherchez par mots-clés, appliquez des filtres personnalisés et examinez chaque détail à la loupe tout en consultant la fiche technique.',
  f3_titulo: 'Chaque pièce, dans son contexte',
  f3_desc:   'Ajoutez vos propres champs et rangez-les à votre goût. Identifiez et documentez chaque pièce en profondeur, avec l’aide des bases de Numista et d’OCRE (monnaie romaine) et de l’intelligence artificielle. Affichez vos monnaies et vos billets, ensemble ou séparément.',
  f4_titulo: 'Idées, rappels et annotations',
  f4_desc:   'Utilisez des pense-bêtes numériques pour garder vos observations et vos tâches en attente. Annotez les photos. Tenez la liste détaillée des pièces que vous cherchez et recevez des rappels aux dates importantes.',
  f5_titulo: 'Un autre regard sur votre collection',
  f5_desc:   'Analysez des statistiques, repérez des tendances et consultez les données clés de votre collection : valeur d’acquisition, valeur actuelle estimée et valeur intrinsèque, avec les cours de l’or et de l’argent mis à jour.',
  f6_titulo: 'Une expérience taillée pour vous',
  f6_desc:   'Personnalisez la façon dont vous affichez et organisez votre collection. Réglez typographies, couleurs, étiquettes, fiches et éléments visuels pour adapter Legado à votre manière de collectionner.',

  faq_titulo: 'Des questions ?',
  faq_sub:    'Voici les réponses aux plus fréquentes',
  faq1_q: 'Legado s’adresse-t-il uniquement aux collectionneurs de monnaies et de billets ?',
  faq1_a: 'Non. Bien qu’il soit conçu spécifiquement pour la numismatique (monnaies, billets, jetons et médailles), son système souple s’adapte sans peine à d’autres types de collections.',
  faq2_q: 'Puis-je utiliser Legado sur mobile ou sur tablette ?',
  faq2_a: 'Pour l’instant, l’application est exclusivement de bureau, disponible pour macOS (Apple Silicon) et Windows (64 bits). Elle est pensée pour travailler confortablement devant un grand écran : fiches détaillées, comparaison de pièces, cartes et étiquettes. Il n’existe pas encore de version pour mobile ni pour tablette.',
  faq3_q: 'Puis-je importer une collection existante ?',
  faq3_a: 'Oui. Vous pouvez récupérer vos données depuis un tableur. Legado vous laisse choisir quelles colonnes importer et à quels champs de l’application les associer. Vous pouvez ensuite modifier les informations une à une ou en bloc. Vous pouvez également importer des images et les attribuer automatiquement à leurs pièces, à partir de codes communs.',
  faq4_q: 'Quel type d’information puis-je ajouter à chaque pièce ?',
  faq4_a: 'Vous pouvez définir des champs personnalisés pour chaque pièce, les organiser comme vous le souhaitez et joindre images, vidéos, documents et liens vers des ressources web ou d’autres fichiers de votre ordinateur. Toute l’information peut s’ajuster à vos besoins.',
  faq5_q: 'Ai-je besoin d’une connexion Internet pour utiliser Legado ?',
  faq5_a: 'L’application fonctionne hors connexion pour la gestion et la consultation des données. Certaines fonctions — les cartes, le calcul de la valeur intrinsèque, la conversion entre devises, l’accès aux bases de Numista et d’OCRE et la génération de contenu par intelligence artificielle — nécessitent une connexion Internet.',
  faq6_q: 'Est-il sûr de télécharger Legado ? Où mes données sont-elles conservées ?',
  faq6_a: 'Oui. Vous pouvez télécharger Legado en toute tranquillité. Le programme n’est distribué que depuis ce site officiel et ne contient ni publicité ni logiciel additionnel. De plus, les données sont stockées localement sur votre appareil ou sur les services de stockage externes que vous configurez vous-même. Legado ne conserve ni ne traite ces données sur ses propres serveurs.',
  faq7_q: 'Dois-je payer un abonnement ?',
  faq7_a: 'Non. Legado Basique est gratuit. La licence de Legado Pro s’acquiert par un paiement unique et n’est liée à aucun abonnement.',
  faq8_q: 'L’usage de Numista et de l’IA a-t-il un coût supplémentaire ?',
  faq8_a: 'L’accès à la base de données de Numista requiert une clé API gratuite, disponible sur Numista.com. La consultation du catalogue OCRE est gratuite et ne demande aucune clé. Précisons que Legado n’est lié ni à Numista ni à OCRE, et n’est pas responsable de leurs conditions, de leur disponibilité ni de leurs tarifs.\n\nPour les fonctions d’intelligence artificielle (génération du contexte historique et identification de pièces à partir d’une photographie), Legado Pro inclut 500 crédits, partagés entre les deux fonctions. Des paquets supplémentaires de 200 crédits peuvent s’acquérir depuis l’application elle-même. Chaque génération de contexte historique coûte 1 crédit. Les requêtes d’identification à partir d’images coûtent de 1 à 5 crédits, selon la fiabilité du résultat.',
  faq9_q: 'Sur combien d’ordinateurs puis-je utiliser Legado Pro ?',
  faq9_a: 'La licence de Legado Pro permet d’utiliser l’application sur deux appareils au plus, simultanément. Vous pouvez en outre désactiver la licence sur un appareil depuis l’application elle-même pour la libérer et l’activer sur un autre, par exemple lorsque vous changez d’ordinateur.',
  faq10_q: 'Comment activer mon Legado Pro ?',
  faq10_a: 'Après le paiement par carte bancaire ou via PayPal, vous recevrez un courrier électronique contenant un code d’activation. Saisissez-le dans la section « Réglages » de l’application.',

  comp_h2:  'Faites passer votre collection\nà la vitesse supérieure',
  comp_sub: 'Commencez par l’essentiel\nou accédez à l’expérience complète',
  cta_titulo: 'Faites de votre collection\nun héritage',
  cta_moneda_alt: 'Tétradrachme d’Athènes à la chouette d’Athéna',
  cta_lupa_hint: 'Passez le curseur sur la monnaie',
  cta_puzzle_hint: 'Reconstituez le tétradrachme et débloquez une surprise',
  cta_puzzle_done: 'Imaginez maintenant votre collection aussi bien rangée.',
  cta_discount_label: '5 % de réduction sur Legado Pro avec le code',
  cta_code_copied: 'Code copié',
  dl_pro_label: 'Legado Pro',
  dl_pro_sub: 'Paiement unique · Expérience complète',
  dl_basic_label: 'Legado Basique',
  dl_basic_sub: 'Gratuit',

  footer_tagline: 'Le musée numérique de votre collection',
  footer_email:   'contacto@legadonumis.com',
  footer_copy:    '© 2026 Legado · legadonumis.com · Tous droits réservés',
  legal_privacidad: 'Politique de confidentialité',
  legal_terminos:   'Conditions d’utilisation',
  legal_reembolso:  'Politique de remboursement',

  nav_link_exp:       'Fonctionnalités',
  nav_link_ver:       'Tarifs',
  nav_link_faq:       'Questions',
  nav_link_contact:   'Contact',
  nav_link_novedades: 'Actualités',
  footer_col_product: 'Produit',
  footer_col_support: 'Assistance',
  footer_col_legal:   'Mentions légales',

  url_download: 'telechargement.html',
  url_privacy:  'confidentialite.html',
  url_terms:    'conditions.html',
  url_refund:   'remboursement.html',

  asset_hero:     '/assets/Hero.mp4',
  asset_sc1:      '/assets/FichaNumista.mp4',
  asset_sc2:      '/assets/FichaCompara.mp4',
  asset_sc3:      '/assets/FichaEtiqueta2.mp4',
  asset_sc4:      '/assets/FichaCecas.mp4',
  asset_sc_anota: '/assets/FichaAnota2.mp4',
  asset_sc_stats: '/assets/FichaStats.mp4',
  asset_sc5:      '/assets/FichaMetas.mp4',
  sc_consultas_titulo: 'Identifiez et cataloguez avec l’aide de l’IA',
  sc_consultas_desc:   'Envoyez la photo d’une monnaie ou d’un billet à identifier. Legado la compare aux catalogues en ligne et, par intelligence artificielle, vous propose l’identification la plus probable.',
  asset_sc_consultas:  '/assets/FichaConsultas.mp4',
  sc_biblioteca_titulo: 'Reliez votre collection\nà votre bibliothèque',
  sc_biblioteca_desc:   'Organisez livres, catalogues, articles et autres documents, et reliez-les directement à vos monnaies et billets pour les avoir toujours à portée de main.',
  asset_sc_biblioteca:  '/assets/FichaBiblio.mp4',


  comp_groups: [
    {
      label: 'Votre collection',
      rows: [
        { feat: 'Pièces enregistrées',                     basico: 'Jusqu’à 50', pro: 'Illimitées' },
        { feat: 'Importation depuis Excel et CSV',         basico: true,         pro: true },
        { feat: 'Importation automatisée de photographies', basico: true,        pro: true },
        { feat: 'Images, vidéos et documents joints',      basico: true,         pro: true },
      ],
    },
    {
      label: 'Documentation et catalogues',
      rows: [
        { feat: 'Consultations de Numista et du catalogue en ligne de monnaies romaines OCRE *', basico: true, pro: true },
        { feat: 'Génération d’informations sur le contexte historique des pièces, avec l’aide de l’intelligence artificielle', basico: false, pro: true },
        { feat: 'Identification et catalogage de pièces, avec l’aide de l’intelligence artificielle', basico: false, pro: true },
        { feat: 'Annotations sur les images', basico: false,       pro: true },
        { feat: 'Notes (Post-it)',            basico: 'Jusqu’à 5', pro: 'Illimitées' },
        { feat: 'Bibliothèque de références bibliographiques avec liaison directe aux pièces', basico: false, pro: true },
      ],
    },
    {
      label: 'Affichage',
      rows: [
        { feat: 'Galerie d’images (6 modes)',        basico: true, pro: true },
        { feat: 'Visionneuse comparative de pièces', basico: true, pro: true },
        { feat: 'Exploration des pièces sur des cartes', basico: true, pro: true },
        { feat: 'Mode clair / Mode sombre',          basico: true, pro: true },
      ],
    },
    {
      label: 'Analyse et planification',
      rows: [
        { feat: 'Statistiques',                   basico: false, pro: true },
        { feat: 'Plan d’acquisitions et rappels', basico: 'Jusqu’à 5 pièces', pro: 'Illimitées' },
      ],
    },
    {
      label: 'Exportation et impression',
      rows: [
        { feat: 'Exportation vers Excel et CSV', basico: 'CSV uniquement', pro: true },
        { feat: 'Exportation de fiches en PDF',  basico: false,            pro: true },
        { feat: 'Générateur d’étiquettes',       basico: false,            pro: true },
      ],
    },
    {
      label: 'Assistance et mises à jour',
      rows: [
        { feat: 'Mises à jour',              basico: true,  pro: true },
        { feat: 'Accès aux nouvelles fonctions', basico: false, pro: true },
        { feat: 'Assistance technique',      basico: false, pro: true },
        { feat: 'Disponible en allemand, anglais, espagnol et français', basico: true, pro: true },
        { feat: 'macOS 11+ (Apple Silicon) · Windows 10+ (64 bits)', basico: true, pro: true },
      ],
    },
  ],
  comp_plan_basic:         'Legado Basique',
  comp_plan_basic_sub:     'Le début de votre musée numérique',
  comp_plan_basic_price:   'Gratuit',
  comp_plan_basic_cta_mac: 'Télécharger\nLegado Basique',
  comp_plan_basic_cta_win: 'Télécharger\nLegado Basique',
  comp_plan_pro:           'Legado Pro',
  comp_plan_pro_sub:       'Votre musée numérique sans limites',
  comp_price_launch:       'Paiement unique\nSans abonnement',
  comp_license_devices:    'Licence pour deux appareils',
  comp_payment_note:       'Paiement sécurisé via LemonSqueezy',
  comp_plan_pro_cta:       'Télécharger\nLegado Pro',
  comp_plan_pro_cta_sub:   'et activer l’expérience Pro',
  comp_footnote1:          '* Les consultations de Numista requièrent une clé API gratuite, disponible sur numista.com.',

  full_precio: '89',

  tm1_quote: 'Les informations de ma collection étaient éparpillées entre des fichiers et des notes. En très peu de temps j’ai tout transféré dans Legado, et maintenant je retrouve n’importe quelle donnée en quelques secondes.',
  tm2_quote: 'Les rappels m’aident à ne pas manquer les ventes en direct qui m’intéressent. Avec Legado je planifie mieux et j’évite les achats impulsifs.',
  tm3_quote: 'J’ai essayé d’autres applications, mais aucune ne me donnait envie de l’ouvrir. Avec Legado ma collection est rangée et, en plus, je m’amuse.',
  tm4_quote: 'Quand j’étudie une pièce, j’aime souligner les légendes, les marques ou de petits détails. Avoir ces annotations directement sur la photographie m’aide à les analyser et à y revenir plus tard.',
  tm5_quote: 'Avant, je préparais les étiquettes une par une. Maintenant je les génère automatiquement, sans recopier les mêmes données sans arrêt, et toujours avec la mise en page que je veux.',
  tm6_quote: 'Chaque collectionneur a sa propre logique. Legado me laisse définir mes champs, mon ordre et mon design. Enfin une application qui s’adapte à moi, et non l’inverse.',
  tm7_quote: 'Je peux désormais relier toute ma documentation de référence à chaque pièce, et y accéder juste au moment où j’en ai besoin.',
  tm8_quote: 'Le plus bel héritage n’est pas seulement de laisser une belle collection. C’est aussi de laisser les clés pour la comprendre, la conserver et la gérer comme il faut.',
}
