export interface CompRow {
  feat: string
  basico: boolean | string
  pro: boolean | string
  cta?: { label: string; url: string }
}

export interface CompGroup {
  label: string
  rows: CompRow[]
}

export interface Content {
  nav_btn_mac: string
  nav_btn_win: string
  hero_h1: string
  hero_sub: string
  hero_btn_mac: string
  hero_btn_win: string
  hero_mobile_notice: string
  pasos_h2: string
  pasos_sub: string
  paso1_titulo: string
  paso1_body: string
  paso2_titulo: string
  paso2_body: string
  paso3_titulo: string
  paso3_body: string
  paso4_titulo: string
  paso4_body: string
  sc_h2: string
  sc_sub: string
  sc1_titulo: string
  sc1_desc: string
  sc2_titulo: string
  sc2_desc: string
  sc3_titulo: string
  sc3_desc: string
  sc4_titulo: string
  sc4_desc: string
  sc_anota_titulo: string
  sc_anota_desc: string
  sc5_titulo: string
  sc5_desc: string
  feat_h2: string
  feat_sub: string
  f1_titulo: string
  f1_desc: string
  f2_titulo: string
  f2_desc: string
  f3_titulo: string
  f3_desc: string
  f4_titulo: string
  f4_desc: string
  f5_titulo: string
  f5_desc: string
  f6_titulo: string
  f6_desc: string
  faq_titulo: string
  faq_sub: string
  faq1_q: string
  faq1_a: string
  faq2_q: string
  faq2_a: string
  faq3_q: string
  faq3_a: string
  faq4_q: string
  faq4_a: string
  faq5_q: string
  faq5_a: string
  faq6_q: string
  faq6_a: string
  faq7_q: string
  faq7_a: string
  faq8_q: string
  faq8_a: string
  comp_h2: string
  comp_sub: string
  cta_titulo: string
  cta_moneda_alt: string
  cta_lupa_hint: string
  cta_puzzle_hint: string
  cta_puzzle_done: string
  cta_discount_label: string
  cta_code_copied: string
  dl_pro_label: string
  dl_pro_sub: string
  dl_basic_label: string
  dl_basic_sub: string
  footer_tagline: string
  footer_email: string
  footer_copy: string
  legal_privacidad: string
  legal_terminos: string
  legal_reembolso: string
  nav_link_exp: string
  nav_link_ver: string
  nav_link_faq: string
  nav_link_contact: string
  nav_link_novedades: string
  footer_col_product: string
  footer_col_support: string
  footer_col_legal: string
  url_download: string
  url_privacy: string
  url_terms: string
  url_refund: string
  asset_hero: string
  asset_sc1: string
  asset_sc2: string
  asset_sc3: string
  asset_sc4: string
  asset_sc_anota: string
  asset_sc5: string
  comp_groups: CompGroup[]
  comp_plan_basic: string
  comp_plan_basic_sub: string
  comp_plan_basic_price: string
  comp_plan_basic_cta_mac: string
  comp_plan_basic_cta_win: string
  comp_plan_pro: string
  comp_plan_pro_sub: string
  comp_price_launch: string
  comp_payment_note: string
  comp_plan_pro_cta: string
  comp_plan_pro_cta_sub: string
  comp_footnote1: string
  comp_footnote2?: string
  trial_badge: string
  trial_precio: string
  trial_nota: string
  trial_items: string[]
  trial_cta: string
  full_tag: string
  full_badge: string
  full_precio: string
  full_divisa: string
  full_nota: string
  full_btn: string
  full_items: string[]
  tm1_quote: string
  tm2_quote: string
  tm3_quote: string
  tm4_quote: string
  tm5_quote: string
  tm6_quote: string
}
